name: 自动签到加继期

on:
  schedule:
    - cron: '0 6 * * *' # 每天UTC时间06:00运行（北京时间14:00）
  workflow_dispatch:  # 允许手动触发
  
jobs:
  add_time_check_in:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    env:
      LEAFLOW_ACCOUNTS: ${{ secrets.LEAFLOW_ACCOUNTS }}
      WEIRDHOST_EMAIL: ${{ secrets.WEIRDHOST_EMAIL }}
      WEIRDHOST_PASSWORD: ${{ secrets.WEIRDHOST_PASSWORD }}
      REMEMBER_WEB_COOKIE: ${{ secrets.REMEMBER_WEB_COOKIE }}
      WEIRDHOST_LOGIN_URL: ${{ secrets.WEIRDHOST_LOGIN_URL }}
      WEIRDHOST_COOKIE_FILE: ${{ secrets.WEIRDHOST_COOKIE_FILE }}
      TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
      TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Playwright and dependencies # 安装 Playwright 及其浏览器依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install --with-deps chromium # 安装 Chromium 浏览器及其运行所需的所有依赖

      - name: Run python Script
        run: python SuperApp.py

      - name: Upload Error Screenshot and cookie.json
        uses: actions/upload-artifact@v4
        if: always() # 总是运行，确保无论前一步成功或失败，都能检查是否有截图需要上传
        with:
          name: error-screenshot and cookie.json
          path: |
            *.png
            *.json
          retention-days: 1
